services:
  valkey:
    build:
      context: ./.docker/valkey
      dockerfile: Dockerfile
    ports:
      - 29100:6379
    command: valkey-server /usr/local/etc/valkey/valkey.conf
    networks:
      - pipewave

  # dynamodb-local:
  #   command: "-jar DynamoDBLocal.jar -port 29101 -sharedDb -dbPath ./data"
  #   image: "amazon/dynamodb-local:latest"
  #   ports:
  #     - "29101:29101"
  #   volumes:
  #     - ./tmp/dynamodb-data:/home/dynamodblocal/data
  #   working_dir: /home/dynamodblocal
  #   networks:
  #     - pipewave

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 5s
    ports:
      - "29102:5432"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
    networks:
      - pipewave

  pipewave-server:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./server-config.example.yaml:/etc/pipewave/config.yaml:ro
    environment:
      APP_SERVER__CALLBACKS__BASE_URL: "http://host.docker.internal:9000/pipewave/callback"
      APP_VALKEY__PRIMARY_ADDRESS: "valkey:6379" # match compose service name/port
      APP_VALKEY__REPLICA_ADDRESS: "valkey:6379"
      APP_POSTGRES__HOST: "postgres" # match compose service name
      APP_POSTGRES__PORT: "5432"
    depends_on:
      - valkey
      - postgres
    networks:
      - pipewave

networks:
  pipewave:
    driver: bridge
