// Code generated by "github.com/pipewave-dev/go-pkg/tools/gen-template-for-enum"; DO NOT EDIT.
// Read doc here: https://github.com/pipewave-dev/go-pkg/tools/-/tree/main/gen-template-for-enum?ref_type=heads

package broadcast

import (
	"context"
	"log/slog"

	otelprv "github.com/pipewave-dev/go-pkg/pkg/otel"
	"github.com/pipewave-dev/go-pkg/pkg/pubsub"
	fncollector "github.com/pipewave-dev/go-pkg/provider/fn-collector"

	"github.com/samber/lo"
)

var isStart map[PubsubHandler]struct{} = make(map[PubsubHandler]struct{})

func StartSubscribers(hdl PubsubHandler,
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) {
	if _, ok := isStart[hdl]; ok {
		return
	}
	isStart[hdl] = struct{}{}
	startSubscriber(hdl, newBroadcastDI(pubsubAdapter, otel, cleanupTask))
}

// For loop generated

// Interface of hanlders
type PubsubHandler interface {
	SendToUser(ctx context.Context, payload SendToUserParams)

	SendToSession(ctx context.Context, payload SendToSessionParams)

	SendToAnonymous(ctx context.Context, payload SendToAnonymousParams)

	DisconnectSession(ctx context.Context, payload DisconnectSessionParams)

	DisconnectUser(ctx context.Context, payload DisconnectUserParams)

	SendToUsers(ctx context.Context, payload SendToUsersParams)

	Broadcast(ctx context.Context, payload BroadcastParams)
}

type _f struct {
	di *broadcastDI
}

func NewMsgCreator(
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) MsgCreator {
	return &_f{
		di: newBroadcastDI(pubsubAdapter, otel, cleanupTask),
	}
}

type MsgCreator interface {
	SendToUser(ctx context.Context, payload SendToUserParams) *pubsubMessage

	SendToSession(ctx context.Context, payload SendToSessionParams) *pubsubMessage

	SendToAnonymous(ctx context.Context, payload SendToAnonymousParams) *pubsubMessage

	DisconnectSession(ctx context.Context, payload DisconnectSessionParams) *pubsubMessage

	DisconnectUser(ctx context.Context, payload DisconnectUserParams) *pubsubMessage

	SendToUsers(ctx context.Context, payload SendToUsersParams) *pubsubMessage

	Broadcast(ctx context.Context, payload BroadcastParams) *pubsubMessage
}

func (f *_f) SendToUser(ctx context.Context, payload SendToUserParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelSendToUser,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func (f *_f) SendToSession(ctx context.Context, payload SendToSessionParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelSendToSession,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func (f *_f) SendToAnonymous(ctx context.Context, payload SendToAnonymousParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelSendToAnonymous,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func (f *_f) DisconnectSession(ctx context.Context, payload DisconnectSessionParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelDisconnectSession,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func (f *_f) DisconnectUser(ctx context.Context, payload DisconnectUserParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelDisconnectUser,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func (f *_f) SendToUsers(ctx context.Context, payload SendToUsersParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelSendToUsers,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func (f *_f) Broadcast(ctx context.Context, payload BroadcastParams) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: channelBroadcast,
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

func startSubscriber(hdl PubsubHandler, di *broadcastDI) {
	unsubscribeAll := make([]func(), 0)
	defer di.cleanupTask.RegTask(func() {
		go func() {
			for _, unsubscribe := range unsubscribeAll {
				unsubscribe()
			}
		}()
	}, fncollector.FnPriorityEarlyest)

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelSendToUser,
			func(msg *pubsubMessage) {
				var payload SendToUserParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type SendToUserParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.SendToUser(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelSendToSession,
			func(msg *pubsubMessage) {
				var payload SendToSessionParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type SendToSessionParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.SendToSession(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelSendToAnonymous,
			func(msg *pubsubMessage) {
				var payload SendToAnonymousParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type SendToAnonymousParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.SendToAnonymous(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelDisconnectSession,
			func(msg *pubsubMessage) {
				var payload DisconnectSessionParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type DisconnectSessionParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.DisconnectSession(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelDisconnectUser,
			func(msg *pubsubMessage) {
				var payload DisconnectUserParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type DisconnectUserParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.DisconnectUser(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelSendToUsers,
			func(msg *pubsubMessage) {
				var payload SendToUsersParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type SendToUsersParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.SendToUsers(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			channelBroadcast,
			func(msg *pubsubMessage) {
				var payload BroadcastParams
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type BroadcastParams", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.Broadcast(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

}
