// Code generated by "github.com/pipewave-dev/go-pkg/tools/gen-template-for-enum"; DO NOT EDIT.

package broadcast

import (
	"context"
	"fmt"
	"log/slog"
	"sync"

	otelprv "github.com/pipewave-dev/go-pkg/pkg/otel"
	"github.com/pipewave-dev/go-pkg/pkg/pubsub"
	configprovider "github.com/pipewave-dev/go-pkg/provider/config-provider"
	fncollector "github.com/pipewave-dev/go-pkg/provider/fn-collector"

	"github.com/samber/lo"
)

var isStart sync.Once

func StartSubscribers(hdl PubsubHandler,
	c configprovider.ConfigStore,
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) {
	isStart.Do(func() {
		startSubscriber(hdl, newBroadcastDI(c, pubsubAdapter, otel, cleanupTask))
	})
}

// For loop generated

// Interface of hanlders
type PubsubHandler interface {
	SendToUser(ctx context.Context, payload SendToUserParams)

	SendToSession(ctx context.Context, payload SendToSessionParams)

	DisconnectSession(ctx context.Context, payload DisconnectSessionParams)

	DisconnectUser(ctx context.Context, payload DisconnectUserParams)

	SendToUsers(ctx context.Context, payload SendToUsersParams)

	SendToSessionWithAck(ctx context.Context, payload SendToSessionWithAckParams)

	SendToUserWithAck(ctx context.Context, payload SendToUserWithAckParams)

	AckResolved(ctx context.Context, payload AckResolvedParams)

	ResumeSession(ctx context.Context, payload ResumeSessionParams)

	SendToAnonymous(ctx context.Context, payload SendToAnonymousParams)

	SendToAuthenticated(ctx context.Context, payload SendToAuthenticatedParams)

	SendToAll(ctx context.Context, payload SendToAllParams)
}

type _f struct {
	di *broadcastDI
}

func NewMsgCreator(
	c configprovider.ConfigStore,
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) MsgCreator {
	return &_f{
		di: newBroadcastDI(c, pubsubAdapter, otel, cleanupTask),
	}
}

type MsgCreator interface {
	SendToUser(ctx context.Context, containerIDs []string, payload SendToUserParams) *pubsubMessage

	SendToSession(ctx context.Context, containerIDs []string, payload SendToSessionParams) *pubsubMessage

	DisconnectSession(ctx context.Context, containerIDs []string, payload DisconnectSessionParams) *pubsubMessage

	DisconnectUser(ctx context.Context, containerIDs []string, payload DisconnectUserParams) *pubsubMessage

	SendToUsers(ctx context.Context, containerIDs []string, payload SendToUsersParams) *pubsubMessage

	SendToSessionWithAck(ctx context.Context, containerIDs []string, payload SendToSessionWithAckParams) *pubsubMessage

	SendToUserWithAck(ctx context.Context, containerIDs []string, payload SendToUserWithAckParams) *pubsubMessage

	AckResolved(ctx context.Context, containerIDs []string, payload AckResolvedParams) *pubsubMessage

	ResumeSession(ctx context.Context, containerIDs []string, payload ResumeSessionParams) *pubsubMessage

	SendToAnonymous(ctx context.Context, payload SendToAnonymousParams) *pubsubMessage

	SendToAuthenticated(ctx context.Context, payload SendToAuthenticatedParams) *pubsubMessage

	SendToAll(ctx context.Context, payload SendToAllParams) *pubsubMessage
}

func (f *_f) SendToUser(ctx context.Context, containerIDs []string, payload SendToUserParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTSendToUser,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) SendToSession(ctx context.Context, containerIDs []string, payload SendToSessionParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTSendToSession,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) DisconnectSession(ctx context.Context, containerIDs []string, payload DisconnectSessionParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTDisconnectSession,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) DisconnectUser(ctx context.Context, containerIDs []string, payload DisconnectUserParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTDisconnectUser,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) SendToUsers(ctx context.Context, containerIDs []string, payload SendToUsersParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTSendToUsers,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) SendToSessionWithAck(ctx context.Context, containerIDs []string, payload SendToSessionWithAckParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTSendToSessionWithAck,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) SendToUserWithAck(ctx context.Context, containerIDs []string, payload SendToUserWithAckParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTSendToUserWithAck,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) AckResolved(ctx context.Context, containerIDs []string, payload AckResolvedParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTAckResolved,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) ResumeSession(ctx context.Context, containerIDs []string, payload ResumeSessionParams) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          msgTResumeSession,
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

func (f *_f) SendToAnonymous(ctx context.Context, payload SendToAnonymousParams) *pubsubMessage {
	return &pubsubMessage{
		sendAllContainers: true,
		context:           ctx,
		msgType:           msgTSendToAnonymous,
		payload:           lo.Must(payload.Marshal()),
		di:                f.di,
	}
}

func (f *_f) SendToAuthenticated(ctx context.Context, payload SendToAuthenticatedParams) *pubsubMessage {
	return &pubsubMessage{
		sendAllContainers: true,
		context:           ctx,
		msgType:           msgTSendToAuthenticated,
		payload:           lo.Must(payload.Marshal()),
		di:                f.di,
	}
}

func (f *_f) SendToAll(ctx context.Context, payload SendToAllParams) *pubsubMessage {
	return &pubsubMessage{
		sendAllContainers: true,
		context:           ctx,
		msgType:           msgTSendToAll,
		payload:           lo.Must(payload.Marshal()),
		di:                f.di,
	}
}

func startSubscriber(hdl PubsubHandler, di *broadcastDI) {
	containerChannel := channelName(di.c.Env().Info.ContainerID)
	broadcastChannel := channelName(broadcastChannel)
	t := &diTmp{
		hdl: hdl,
		di:  di,
	}

	var (
		unsubscribeContainerChannel func()
		unsubscribeBroadcastChannel func()
		err                         error
	)

	defer di.cleanupTask.RegTask(func() {
		unsubscribeContainerChannel()
		unsubscribeBroadcastChannel()
	}, fncollector.FnPriorityEarlyest)

	{
		unsubscribeContainerChannel, err = di.pubsub.Subscribe(
			containerChannel,
			t.handleMsg,
		)
		if err != nil {
			panic(err)
		}
	}
	{
		unsubscribeBroadcastChannel, err = di.pubsub.Subscribe(
			broadcastChannel,
			t.handleBroadcastMsg,
		)
		if err != nil {
			panic(err)
		}
	}
}

type diTmp struct {
	hdl PubsubHandler
	di  *broadcastDI
}

func (t *diTmp) handleMsg(msg *pubsubMessage) {
	ctx, _ := t.di.otel.Extract(
		msg.GetContext(),
		msg.GetOtelCarrier())

	switch msg.GetMsgType() {

	case msgTSendToUser:
		{
			var payload SendToUserParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToUserParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToUser(ctx, payload)
		}

	case msgTSendToSession:
		{
			var payload SendToSessionParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToSessionParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToSession(ctx, payload)
		}

	case msgTDisconnectSession:
		{
			var payload DisconnectSessionParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type DisconnectSessionParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.DisconnectSession(ctx, payload)
		}

	case msgTDisconnectUser:
		{
			var payload DisconnectUserParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type DisconnectUserParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.DisconnectUser(ctx, payload)
		}

	case msgTSendToUsers:
		{
			var payload SendToUsersParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToUsersParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToUsers(ctx, payload)
		}

	case msgTSendToSessionWithAck:
		{
			var payload SendToSessionWithAckParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToSessionWithAckParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToSessionWithAck(ctx, payload)
		}

	case msgTSendToUserWithAck:
		{
			var payload SendToUserWithAckParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToUserWithAckParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToUserWithAck(ctx, payload)
		}

	case msgTAckResolved:
		{
			var payload AckResolvedParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type AckResolvedParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.AckResolved(ctx, payload)
		}

	case msgTResumeSession:
		{
			var payload ResumeSessionParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type ResumeSessionParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.ResumeSession(ctx, payload)
		}

	default:
		slog.Error("Unexpected pubsub MsgType")
	}
}

func (t *diTmp) handleBroadcastMsg(msg *pubsubMessage) {
	ctx, _ := t.di.otel.Extract(
		msg.GetContext(),
		msg.GetOtelCarrier())

	switch msg.GetMsgType() {

	case msgTSendToAnonymous:
		{
			var payload SendToAnonymousParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToAnonymousParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToAnonymous(ctx, payload)
		}

	case msgTSendToAuthenticated:
		{
			var payload SendToAuthenticatedParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToAuthenticatedParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToAuthenticated(ctx, payload)
		}

	case msgTSendToAll:
		{
			var payload SendToAllParams
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type SendToAllParams", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.SendToAll(ctx, payload)
		}

	default:
		slog.Error(fmt.Sprintf("Unexpected pubsub MsgType: %v", msg.GetMsgType()))
	}
}
