// Code generated by "github.com/pipewave-dev/go-pkg/tools/gen-template-for-enum"; DO NOT EDIT.
// Read doc here: https://github.com/pipewave-dev/go-pkg/tools/-/tree/main/gen-template-for-enum?ref_type=heads

package {{.PackageName}}

import (
	"context"
	"log/slog"

	fncollector "github.com/pipewave-dev/go-pkg/provider/fn-collector"
	otelprv "github.com/pipewave-dev/go-pkg/pkg/otel"
	"github.com/pipewave-dev/go-pkg/pkg/pubsub"

	"github.com/samber/lo"
)


var isStart map[PubsubHandler]struct{} = make(map[PubsubHandler]struct{})

func StartSubscribers(hdl PubsubHandler,
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) {
	if _, ok := isStart[hdl]; ok {
		return
	}
	isStart[hdl] = struct{}{}
	startSubscriber(hdl, newBroadcastDI(pubsubAdapter, otel, cleanupTask))
}

// For loop generated


// Interface of hanlders
type PubsubHandler interface {
{{range $val := .EnumValues}}
{{ $ChannelName := $val.Name }}
{{ $FuncName := trimPrefix "channel" $ChannelName }}
{{ $payloadType := (printf "%v" (index $val.DocComment 0)) }}

  {{ $FuncName }}(ctx context.Context, payload {{ $payloadType }})

{{end}}
}

type _f struct{
	di *broadcastDI
}

func NewMsgCreator(
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) MsgCreator {
	return &_f{
		di: newBroadcastDI(pubsubAdapter, otel, cleanupTask),
	}
}

type MsgCreator interface {
{{range $val := .EnumValues}}
{{ $ChannelName := $val.Name }}
{{ $FuncName := trimPrefix "channel" $ChannelName }}
{{ $payloadType := (printf "%v" (index $val.DocComment 0)) }}

  {{ $FuncName }}(ctx context.Context, payload {{ $payloadType }}) *pubsubMessage

{{end}}
}


{{range $val := .EnumValues}}
{{ $ChannelName := $val.Name }}
{{ $FuncName := trimPrefix "channel" $ChannelName }}
{{ $payloadType := (printf "%v" (index $val.DocComment 0)) }}

func (f *_f) {{ $FuncName }}(ctx context.Context, payload {{ $payloadType }}) *pubsubMessage {
	return &pubsubMessage{
		context: ctx,
		channel: {{ $ChannelName }},
		payload: lo.Must(payload.Marshal()),
        di: f.di,
	}
}

{{end}}

func startSubscriber(hdl PubsubHandler, di *broadcastDI) {
	unsubscribeAll := make([]func(), 0)
	defer di.cleanupTask.RegTask(func() {
		go func() {
			for _, unsubscribe := range unsubscribeAll {
				unsubscribe()
			}
		}()
	}, fncollector.FnPriorityEarlyest)

{{range $val := .EnumValues}}
{{ $ChannelName := $val.Name }}
{{ $FuncName := trimPrefix "channel" $ChannelName }}
{{ $payloadType := (printf "%v" (index $val.DocComment 0)) }}

	{
		unsubscribe, err := di.pubsub.Subscribe(
			{{ $ChannelName }},
			func(msg *pubsubMessage) {
				var payload {{ $payloadType }}
				err := payload.Unmarshal(msg.GetPayload())
				if err != nil {
					slog.Error("subscriber wrong type {{ $payloadType }}", "error", err, "channel", msg.GetChannel())
					return
				}
				ctx, _ := di.otel.Extract(msg.GetContext(), msg.GetOtelCarrier())
				hdl.{{ $FuncName }}(ctx, payload)
			},
		)
		if err != nil {
			panic(err)
		}
		unsubscribeAll = append(unsubscribeAll, unsubscribe)
	}

{{end}}
}
