// Code generated by "github.com/pipewave-dev/go-pkg/tools/gen-template-for-enum"; DO NOT EDIT.

package {{.PackageName}}

import (
	"context"
	"log/slog"
	"sync"

	otelprv "github.com/pipewave-dev/go-pkg/pkg/otel"
	"github.com/pipewave-dev/go-pkg/pkg/pubsub"
	configprovider "github.com/pipewave-dev/go-pkg/provider/config-provider"
	fncollector "github.com/pipewave-dev/go-pkg/provider/fn-collector"

	"github.com/samber/lo"
)

var isStart sync.Once

func StartSubscribers(hdl PubsubHandler,
	c configprovider.ConfigStore,
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) {
	isStart.Do(func() {
		startSubscriber(hdl, newBroadcastDI(c, pubsubAdapter, otel, cleanupTask))
	})
}

// For loop generated

// Interface of hanlders
type PubsubHandler interface {
{{range $val := .EnumValues}}
{{ $MsgTypeName := $val.Name }}
{{ $FuncName := trimPrefix "msgT" $MsgTypeName }}
{{ $payloadType := "[]byte" }}
{{ if gt (len $val.DocComment) 0 }}
{{ $payloadType = (printf "%v" (index $val.DocComment 0)) }}
{{ end }}

  {{ $FuncName }}(ctx context.Context, payload {{ $payloadType }})

{{end}}
}


type _f struct {
	di *broadcastDI
}

func NewMsgCreator(
	c configprovider.ConfigStore,
	pubsubAdapter pubsub.Adapter,
	otel otelprv.OtelProvider,
	cleanupTask fncollector.CleanupTask,
) MsgCreator {
	return &_f{
		di: newBroadcastDI(c, pubsubAdapter, otel, cleanupTask),
	}
}

type MsgCreator interface {
{{range $val := .EnumValues}}
{{ $MsgTypeName := $val.Name }}
{{ $FuncName := trimPrefix "msgT" $MsgTypeName }}
{{ $payloadType := "[]byte" }}
{{ if gt (len $val.DocComment) 0 }}
{{ $payloadType = (printf "%v" (index $val.DocComment 0)) }}
{{ end }}
{{ $pubsubType := "Broadcast" }}
{{ if gt (len $val.BlockDocComment) 0 }}
{{ $pubsubType = (printf "%v" (index $val.BlockDocComment 0)) }}
{{ end }}

	{{ if eq $pubsubType "Targeted" }}
  {{ $FuncName }}(ctx context.Context, containerIDs []string, payload {{ $payloadType }}) *pubsubMessage
  {{ else }}
  {{ $FuncName }}(ctx context.Context, payload {{ $payloadType }}) *pubsubMessage
  {{ end }}

{{end}}
}


{{range $val := .EnumValues}}
{{ $MsgTypeName := $val.Name }}
{{ $FuncName := trimPrefix "msgT" $MsgTypeName }}
{{ $payloadType := "[]byte" }}
{{ if gt (len $val.DocComment) 0 }}
{{ $payloadType = (printf "%v" (index $val.DocComment 0)) }}
{{ end }}
{{ $pubsubType := "Broadcast" }}
{{ if gt (len $val.BlockDocComment) 0 }}
{{ $pubsubType = (printf "%v" (index $val.BlockDocComment 0)) }}
{{ end }}

{{ if eq $pubsubType "Targeted" }}
func (f *_f) {{ $FuncName }}(ctx context.Context, containerIDs []string, payload {{ $payloadType }}) *pubsubMessage {
	return &pubsubMessage{
		targetContainers: containerIDs,
		context:          ctx,
		msgType:          {{ $MsgTypeName }},
		payload:          lo.Must(payload.Marshal()),
		di:               f.di,
	}
}

{{ else }}
func (f *_f) {{ $FuncName }}(ctx context.Context, payload {{ $payloadType }}) *pubsubMessage {
	return &pubsubMessage{
		sendAllContainers: true,
		context: ctx,
		msgType: {{ $MsgTypeName }},
		payload: lo.Must(payload.Marshal()),
		di:      f.di,
	}
}

{{ end }}

{{end}}

func startSubscriber(hdl PubsubHandler, di *broadcastDI) {
	containerChannel := channelName(di.c.Env().ContainerID)
	broadcastChannel := channelName(broadcastChannel)
	t := &diTmp{
		hdl: hdl,
		di:  di,
	}

	var (
		unsubscribeContainerChannel func()
		unsubscribeBroadcastChannel func()
		err                         error
	)

	defer di.cleanupTask.RegTask(func() {
		unsubscribeContainerChannel()
		unsubscribeBroadcastChannel()
	}, fncollector.FnPriorityEarlyest)

	{
		unsubscribeContainerChannel, err = di.pubsub.Subscribe(
			containerChannel,
			t.handleMsg,
		)
		if err != nil {
			panic(err)
		}
	}
	{
		unsubscribeBroadcastChannel, err = di.pubsub.Subscribe(
			broadcastChannel,
			t.handleBroadcastMsg,
		)
		if err != nil {
			panic(err)
		}
	}
}

type diTmp struct {
	hdl PubsubHandler
	di  *broadcastDI
}

func (t *diTmp) handleMsg(msg *pubsubMessage) {
	ctx, _ := t.di.otel.Extract(
		msg.GetContext(),
		msg.GetOtelCarrier())

	switch msg.GetMsgType() {
{{range $val := .EnumValues}}
{{ $MsgTypeName := $val.Name }}
{{ $FuncName := trimPrefix "msgT" $MsgTypeName }}
{{ $payloadType := "[]byte" }}
{{ if gt (len $val.DocComment) 0 }}
{{ $payloadType = (printf "%v" (index $val.DocComment 0)) }}
{{ end }}
{{ $pubsubType := "Broadcast" }}
{{ if gt (len $val.BlockDocComment) 0 }}
{{ $pubsubType = (printf "%v" (index $val.BlockDocComment 0)) }}
{{ end }}
{{ if eq $pubsubType "Targeted" }}
	case {{ $MsgTypeName }}:
		{
			var payload {{ $payloadType }}
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type {{ $payloadType }}", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.{{ $FuncName }}(ctx, payload)
		}
{{ end }}
{{ end }}
	}
}

func (t *diTmp) handleBroadcastMsg(msg *pubsubMessage) {
	ctx, _ := t.di.otel.Extract(
		msg.GetContext(),
		msg.GetOtelCarrier())

	switch msg.GetMsgType() {
{{range $val := .EnumValues}}
{{ $MsgTypeName := $val.Name }}
{{ $FuncName := trimPrefix "msgT" $MsgTypeName }}
{{ $payloadType := "[]byte" }}
{{ if gt (len $val.DocComment) 0 }}
{{ $payloadType = (printf "%v" (index $val.DocComment 0)) }}
{{ end }}
{{ $pubsubType := "Broadcast" }}
{{ if gt (len $val.BlockDocComment) 0 }}
{{ $pubsubType = (printf "%v" (index $val.BlockDocComment 0)) }}
{{ end }}
{{ if ne $pubsubType "Targeted" }}
	case {{ $MsgTypeName }}:
		{
			var payload {{ $payloadType }}
			err := payload.Unmarshal(msg.GetPayload())
			if err != nil {
				slog.Error("subscriber wrong type {{ $payloadType }}", "error", err, "msgType", msg.GetMsgType())
				return
			}
			t.hdl.{{ $FuncName }}(ctx, payload)
		}

{{ end }}
{{end}}
	}
}
