// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"
	"time"

	moduledelivery "github.com/pipewave-dev/go-pkg/core/delivery/module"
	"github.com/pipewave-dev/go-pkg/core/repository"
	"github.com/pipewave-dev/go-pkg/core/service/business/monitoring"
	ackmanager "github.com/pipewave-dev/go-pkg/core/service/websocket/ack-manager"
	broadcastmsghandler "github.com/pipewave-dev/go-pkg/core/service/websocket/broadcast-msg-handler"
	clientmsghandler "github.com/pipewave-dev/go-pkg/core/service/websocket/client-msg-handler"
	connectionmanager "github.com/pipewave-dev/go-pkg/core/service/websocket/connection-manager"
	exchangetoken "github.com/pipewave-dev/go-pkg/core/service/websocket/exchange-token"
	delivery "github.com/pipewave-dev/go-pkg/core/service/websocket/mediator/delivery"
	mediatorsvc "github.com/pipewave-dev/go-pkg/core/service/websocket/mediator/service"
	msghub "github.com/pipewave-dev/go-pkg/core/service/websocket/msg-hub"
	ratelimiter "github.com/pipewave-dev/go-pkg/core/service/websocket/rate-limiter"
	wseventtrigger "github.com/pipewave-dev/go-pkg/core/service/websocket/ws-event-trigger"
	cacheprovider "github.com/pipewave-dev/go-pkg/provider/cache-provider"
	configprovider "github.com/pipewave-dev/go-pkg/provider/config-provider"
	fncollector "github.com/pipewave-dev/go-pkg/provider/fn-collector"
	healthyprovider "github.com/pipewave-dev/go-pkg/provider/healthy-provider"
	muxmiddleware "github.com/pipewave-dev/go-pkg/provider/mux-middleware"
	observerprovider "github.com/pipewave-dev/go-pkg/provider/observer-provider"
	otelprovider "github.com/pipewave-dev/go-pkg/provider/otel-provider"
	pubsubfactory "github.com/pipewave-dev/go-pkg/provider/pubsub"
	queuefactory "github.com/pipewave-dev/go-pkg/provider/queue"
	workerpoolprovider "github.com/pipewave-dev/go-pkg/provider/worker-pool-provider"

	_ "github.com/pipewave-dev/go-pkg/shared/aerror"
)

// Injectors from wire.go:

func NewPipewave(config configprovider.ConfigStore, s *slog.Logger, rf repository.RepoFactory, qf queuefactory.QueueFactory, pf pubsubfactory.PubsubFactory) *AppDI {
	middlewareProvider := muxmiddleware.New(config)
	v := healthyprovider.New(config)
	cleanupTask := fncollector.NewCleanupTask()
	workerPool := workerpoolprovider.New(config, v, cleanupTask)
	otelProvider := otelprovider.New(config, cleanupTask)
	observability := observerprovider.New(config, otelProvider, s)
	allRepository := RepoProvider(rf, config, observability)
	connectionManager := connectionmanager.Singleton()
	adapter := PubsubProvider(pf, config, cleanupTask)
	ackManager := ackmanager.New()
	// TODO: replace 5*time.Minute with c.Ws().TempDisconnectTTL() once config exposes it.
	msgHubSvc := msghub.New(allRepository.PendingMessage(), 5*time.Minute)
	shutdownSignal := msghub.NewShutdownSignal()
	pubsubHandler := broadcastmsghandler.New(allRepository, connectionManager, ackManager, msgHubSvc, workerPool)
	wsService := mediatorsvc.New(config, allRepository, cleanupTask, workerPool, connectionManager, pubsubHandler, adapter, otelProvider, ackManager, msgHubSvc, shutdownSignal)
	rateLimiter := ratelimiter.New(config)
	intervalTask := fncollector.NewIntervalTask()
	clientMsgHandler := clientmsghandler.New(config, cleanupTask, intervalTask, observability, adapter, otelProvider, rateLimiter, allRepository, ackManager)
	cacheProvider := cacheprovider.New(config, cleanupTask)
	exchangeToken := exchangetoken.New(observability, cacheProvider)
	queueAdapter := QueueProvider(qf, config, cleanupTask)
	onNewStuffFn := wseventtrigger.NewOnNewStuff(config)
	onCloseStuffFn := wseventtrigger.NewOnCloseStuff(config)
	serverDelivery := delivery.New(config, workerPool, v, wsService, connectionManager, rateLimiter, clientMsgHandler, exchangeToken, allRepository, queueAdapter, onNewStuffFn, onCloseStuffFn, msgHubSvc, shutdownSignal)
	businessMonitoring := monitoring.New(allRepository, connectionManager, workerPool, observability, cacheProvider)
	moduleDelivery := moduledelivery.New(config, middlewareProvider, serverDelivery, wsService, onNewStuffFn, onCloseStuffFn, v, businessMonitoring, workerPool, cleanupTask, intervalTask)
	appDI := NewAppDI(moduleDelivery)
	return appDI
}
