// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/pipewave-dev/go-pkg/core/delivery/module"
	"github.com/pipewave-dev/go-pkg/core/repository"
	"github.com/pipewave-dev/go-pkg/core/service/business/monitoring"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/ack-manager"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/broadcast-msg-handler"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/client-msg-handler"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/connection-manager"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/exchange-token"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/mediator/delivery"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/mediator/service"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/rate-limiter"
	"github.com/pipewave-dev/go-pkg/core/service/websocket/ws-event-trigger"
	"github.com/pipewave-dev/go-pkg/provider/cache-provider"
	"github.com/pipewave-dev/go-pkg/provider/config-provider"
	"github.com/pipewave-dev/go-pkg/provider/fn-collector"
	"github.com/pipewave-dev/go-pkg/provider/healthy-provider"
	"github.com/pipewave-dev/go-pkg/provider/mux-middleware"
	"github.com/pipewave-dev/go-pkg/provider/observer-provider"
	"github.com/pipewave-dev/go-pkg/provider/otel-provider"
	"github.com/pipewave-dev/go-pkg/provider/pubsub-provider"
	"github.com/pipewave-dev/go-pkg/provider/queue"
	"github.com/pipewave-dev/go-pkg/provider/worker-pool-provider"
	"log/slog"
)

import (
	_ "github.com/pipewave-dev/go-pkg/shared/aerror"
)

// Injectors from wire.go:

func NewPipewave(config configprovider.ConfigStore, s *slog.Logger, rf repository.RepoFactory, qf queue.QueueFactory) *AppDI {
	middlewareProvider := muxmiddleware.New(config)
	v := healthyprovider.New(config)
	cleanupTask := fncollector.NewCleanupTask()
	workerPool := workerpoolprovider.New(config, v, cleanupTask)
	otelProvider := otelprovider.New(config, cleanupTask)
	observability := observerprovider.New(config, otelProvider, s)
	allRepository := RepoProvider(rf, config, observability)
	connectionManager := connectionmanager.Singleton()
	pubsubHandler := broadcastmsghandler.New(allRepository, connectionManager)
	adapter := pubsubprovider.New(config, cleanupTask)
	ackMgr := ackmanager.New()
	wsService := mediatorsvc.New(allRepository, cleanupTask, workerPool, connectionManager, pubsubHandler, adapter, otelProvider, ackMgr)
	rateLimiter := ratelimiter.New(config)
	intervalTask := fncollector.NewIntervalTask()
	clientMsgHandler := clientmsghandler.New(config, cleanupTask, intervalTask, observability, adapter, otelProvider, rateLimiter, allRepository, ackMgr)
	cacheProvider := cacheprovider.New(config, cleanupTask)
	exchangeToken := exchangetoken.New(observability, cacheProvider)
	queueAdapter := QueueProvider(qf, config, cleanupTask)
	onNewStuffFn := wseventtrigger.NewOnNewStuff(config)
	onCloseStuffFn := wseventtrigger.NewOnCloseStuff(config)
	serverDelivery := delivery.New(config, workerPool, v, wsService, connectionManager, rateLimiter, clientMsgHandler, exchangeToken, allRepository, queueAdapter, onNewStuffFn, onCloseStuffFn)
	businessMonitoring := monitoring.New(allRepository, connectionManager, workerPool, observability, cacheProvider)
	moduleDelivery := moduledelivery.New(config, middlewareProvider, serverDelivery, wsService, onNewStuffFn, onCloseStuffFn, v, businessMonitoring, workerPool, cleanupTask, intervalTask)
	appDI := NewAppDI(moduleDelivery)
	return appDI
}
